name: Build and Publish Docker Image

on:
  push:
    branches:
      - main  # O la rama que prefieras

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker-compose -f docker-compose.yml build
        docker tag your-image-name ghcr.io/${{ github.repository_owner }}/your-image-name:latest
        docker push ghcr.io/${{ github.repository_owner }}/your-image-name:latest
